### ISSUE TITLE
User management Page

### ISSUE THREAD

**Issue by miguel-merlin** [stevensblueprint/blueprint_admin#16]
## Roadmap
- [ ] Create table to see active users
- [ ] Create button to add users
- [ ] Create form to add users
- [ ] Edit user information, including permissions
- [ ] See user statistics such as % of users added in the past week, role of users, class, major
