### ISSUE TITLE
Application Management Page

### ISSUE THREAD

**Issue by miguel-merlin** [stevensblueprint/blueprint_admin#17]
## Roadmap
- [ ] Create a new Application Cycle
- [ ] Form to submit application
- [ ] Form to submit interest form
- [ ] View table of applications
- [ ] View statistics on the application such as class, major, role, % of applicants who submitted the application
